In [14]:
import numpy as np
import pandas as pd


import os
for dirname, _, filenames in os.walk('/kaggle/input'):
    for filename in filenames:
        print(os.path.join(dirname, filename))



In [15]:
import pandas as pd

file_path = '/content/drive/My Drive/dataset/Metabolic Syndrome.csv'
data = pd.read_csv(file_path)

data.head()


seqn  Age     Sex  Marital  Income   Race  WaistCirc   BMI  Albuminuria  \
0  62161   22    Male   Single  8200.0  White       81.0  23.3            0   
1  62164   44  Female  Married  4500.0  White       80.1  23.2            0   
2  62169   21    Male   Single   800.0  Asian       69.6  20.1            0   
3  62172   43  Female   Single  2000.0  Black      120.4  33.3            0   
4  62177   51    Male  Married     NaN  Asian       81.1  20.1            0   

   UrAlbCr  UricAcid  BloodGlucose  HDL  Triglycerides  MetabolicSyndrome  
0     3.88       4.9            92   41             84                  0  
1     8.55       4.5            82   28             56                  0  
2     5.07       5.4           107   43             78                  0  
3     5.22       5.0           104   73            141                  0  
4     8.13       5.0            95   43            126                  0

In [16]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import RandomForestClassifier
from sklearn.metrics import classification_report, confusion_matrix



In [17]:

data.fillna(method='ffill', inplace=True)
data.fillna(method='bfill', inplace=True)

<ipython-input-17-5becf6a76c4a>:1: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)
<ipython-input-17-5becf6a76c4a>:2: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill', inplace=True)


In [18]:
data = pd.get_dummies(data, columns=['Sex', 'Marital', 'Race'])


X = data.drop(columns=['MetabolicSyndrome'])
y = data['MetabolicSyndrome']

In [19]:

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)


In [20]:


scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)


In [21]:

classifier = RandomForestClassifier(n_estimators=100, random_state=42)
classifier.fit(X_train, y_train)


RandomForestClassifier(random_state=42)

In [22]:
y_pred = classifier.predict(X_test)

print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[301  23]
 [ 38 119]]

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.93      0.91       324
           1       0.84      0.76      0.80       157

    accuracy                           0.87       481
   macro avg       0.86      0.84      0.85       481
weighted avg       0.87      0.87      0.87       481



**Support Vector Machine**

In [23]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.svm import SVC
from sklearn.metrics import classification_report, confusion_matrix



In [26]:
data = pd.read_csv('/content/drive/My Drive/dataset/Metabolic Syndrome.csv')

data.fillna(method='ffill', inplace=True)
data.fillna(method='bfill', inplace=True)

data = pd.get_dummies(data, columns=['Sex', 'Marital', 'Race'])

X = data.drop(columns=['MetabolicSyndrome'])
y = data['MetabolicSyndrome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

svm_classifier = SVC(kernel='linear', random_state=42)
svm_classifier.fit(X_train, y_train)

y_pred = svm_classifier.predict(X_test)


print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))


<ipython-input-26-d4e99408fc82>:3: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)
<ipython-input-26-d4e99408fc82>:4: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill', inplace=True)


Confusion Matrix:
 [[293  31]
 [ 60  97]]

Classification Report:
               precision    recall  f1-score   support

           0       0.83      0.90      0.87       324
           1       0.76      0.62      0.68       157

    accuracy                           0.81       481
   macro avg       0.79      0.76      0.77       481
weighted avg       0.81      0.81      0.81       481



**Logistic Regression**

In [28]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.linear_model import LogisticRegression
from sklearn.metrics import classification_report, confusion_matrix

data = pd.read_csv('/content/drive/My Drive/dataset/Metabolic Syndrome.csv')

data.fillna(method='ffill', inplace=True)
data.fillna(method='bfill', inplace=True)

data = pd.get_dummies(data, columns=['Sex', 'Marital', 'Race'])

X = data.drop(columns=['MetabolicSyndrome'])
y = data['MetabolicSyndrome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

logistic_classifier = LogisticRegression(random_state=42)
logistic_classifier.fit(X_train, y_train)

y_pred = logistic_classifier.predict(X_test)

<ipython-input-28-32e77b1a401b>:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)
<ipython-input-28-32e77b1a401b>:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill', inplace=True)


In [29]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[296  28]
 [ 58  99]]

Classification Report:
               precision    recall  f1-score   support

           0       0.84      0.91      0.87       324
           1       0.78      0.63      0.70       157

    accuracy                           0.82       481
   macro avg       0.81      0.77      0.79       481
weighted avg       0.82      0.82      0.82       481



**Gradient Boosting Classifier **

In [31]:

import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.ensemble import GradientBoostingClassifier
from sklearn.metrics import classification_report, confusion_matrix


data = pd.read_csv('/content/drive/My Drive/dataset/Metabolic Syndrome.csv')

data.fillna(method='ffill', inplace=True)
data.fillna(method='bfill', inplace=True)

data = pd.get_dummies(data, columns=['Sex', 'Marital', 'Race'])

X = data.drop(columns=['MetabolicSyndrome'])
y = data['MetabolicSyndrome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

gb_classifier = GradientBoostingClassifier(random_state=42)
gb_classifier.fit(X_train, y_train)

y_pred = gb_classifier.predict(X_test)



<ipython-input-31-3eccb7f8cea5>:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)
<ipython-input-31-3eccb7f8cea5>:11: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill', inplace=True)


In [32]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[298  26]
 [ 35 122]]

Classification Report:
               precision    recall  f1-score   support

           0       0.89      0.92      0.91       324
           1       0.82      0.78      0.80       157

    accuracy                           0.87       481
   macro avg       0.86      0.85      0.85       481
weighted avg       0.87      0.87      0.87       481



**KNN **

In [34]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import StandardScaler
from sklearn.neighbors import KNeighborsClassifier
from sklearn.metrics import classification_report, confusion_matrix

data = pd.read_csv('/content/drive/My Drive/dataset/Metabolic Syndrome.csv')

data.fillna(method='ffill', inplace=True)
data.fillna(method='bfill', inplace=True)

data = pd.get_dummies(data, columns=['Sex', 'Marital', 'Race'])

X = data.drop(columns=['MetabolicSyndrome'])
y = data['MetabolicSyndrome']

X_train, X_test, y_train, y_test = train_test_split(X, y, test_size=0.2, random_state=42)

scaler = StandardScaler()
X_train = scaler.fit_transform(X_train)
X_test = scaler.transform(X_test)

knn_classifier = KNeighborsClassifier()
knn_classifier.fit(X_train, y_train)

y_pred = knn_classifier.predict(X_test)

<ipython-input-34-7a5ec5e47863>:9: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='ffill', inplace=True)
<ipython-input-34-7a5ec5e47863>:10: FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
  data.fillna(method='bfill', inplace=True)


In [35]:
print("Confusion Matrix:\n", confusion_matrix(y_test, y_pred))
print("\nClassification Report:\n", classification_report(y_test, y_pred))

Confusion Matrix:
 [[281  43]
 [ 71  86]]

Classification Report:
               precision    recall  f1-score   support

           0       0.80      0.87      0.83       324
           1       0.67      0.55      0.60       157

    accuracy                           0.76       481
   macro avg       0.73      0.71      0.72       481
weighted avg       0.76      0.76      0.76       481

